baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'AAA (Alterated Alternity Alternative)'
theme = 'ananke'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
