
# General Skills Data
SKILLS_DATA = [
    {"a":"STR","s":[{"n":"Armor Operation","u":"YES","at":"STR","sp":[{"n":"Combat armor","at":"STR","u":"YES"},{"n":"Powered armor","at":"STR","u":"YES"},{"n":"Tactical armor","at":"INT","u":"YES"},{"n":"Propulsion systems","at":"INT","u":"YES"},{"n":"Shields","at":"STR","u":"YES"}]},{"n":"Athletics","u":"YES","at":"STR","sp":[{"n":"Climb","at":"STR","u":"YES"},{"n":"Jump","at":"STR","u":"YES"},{"n":"Swim","at":"CON","u":"YES"},{"n":"Throw","at":"STR","u":"YES"}]},{"n":"Heavy Weapons","u":"YES","at":"STR","sp":[{"n":"Direct fire","at":"STR","u":"YES"},{"n":"Indirect fire","at":"STR","u":"YES"}]},{"n":"Melee Combat","u":"YES","at":"STR","sp":[{"n":"Blade","at":"STR","u":"YES"},{"n":"Blunt","at":"STR","u":"YES"},{"n":"Defensive Martial Arts","at":"DEX","u":"NO"},{"n":"Power Martial Arts","at":"STR","u":"NO"},{"n":"Powered","at":"DEX","u":"YES"}]}]},
    {"a":"DEX","s":[{"n":"Acrobatics","u":"YES","at":"DEX","sp":[{"n":"Daredevil","at":"DEX","u":"YES"},{"n":"Dodge","at":"DEX","u":"YES"},{"n":"Fall","at":"DEX","u":"YES"},{"n":"Zero-g Training","at":"DEX","u":"NO"},{"n":"Aerobatics","at":"DEX","u":"YES"}]},{"n":"Covert Ops","u":"YES","at":"DEX","sp":[{"n":"Conceal","at":"DEX","u":"YES"},{"n":"Disguise","at":"CHA","u":"YES"},{"n":"Pickpocket","at":"DEX","u":"NO"},{"n":"Stealth","at":"DEX","u":"YES"}]},{"n":"Modern Ranged Weapons","u":"YES","at":"DEX","sp":[{"n":"Assault Rifle","at":"DEX","u":"YES"},{"n":"Pistol","at":"DEX","u":"YES"},{"n":"Rifle","at":"DEX","u":"YES"},{"n":"Shotgun","at":"DEX","u":"YES"},{"n":"SMG","at":"DEX","u":"YES"}]},{"n":"Primitive Ranged Weapons","u":"YES","at":"DEX","sp":[{"n":"Bow","at":"DEX","u":"YES"},{"n":"Crossbow","at":"DEX","u":"YES"},{"n":"Flintlock","at":"DEX","u":"YES"},{"n":"Sling","at":"DEX","u":"YES"}]},{"n":"Vehicle Operation","u":"YES","at":"DEX","sp":[{"n":"Air vehicle","at":"DEX","u":"NO"},{"n":"Land vehicle","at":"DEX","u":"YES"},{"n":"Space vehicle","at":"DEX","u":"NO"},{"n":"Water vehicle","at":"DEX","u":"YES"}]}]},
    {"a":"CON","s":[{"n":"Stamina","u":"YES","at":"CON","sp":[{"n":"Endurance","at":"CON","u":"YES"},{"n":"Resist pain","at":"CON","u":"NO"}]},{"n":"Survival","u":"YES","at":"CON","sp":[{"n":"Survival training","at":"CON","u":"YES"},{"n":"Adaptability","at":"CON","u":"NO"},{"n":"Trailblazing","at":"CON","u":"YES"}]}]},
    {"a":"INT","s":[{"n":"Administration","u":"YES","at":"INT","sp":[{"n":"Bureaucracy","at":"INT","u":"YES"},{"n":"Management","at":"INT","u":"YES"}]},{"n":"Business","u":"YES","at":"INT","sp":[{"n":"Corporate","at":"INT","u":"YES"},{"n":"Illicit business","at":"INT","u":"YES"},{"n":"Small business","at":"INT","u":"YES"}]},{"n":"Computer Science","u":"YES","at":"INT","sp":[{"n":"Hacking","at":"INT","u":"NO"},{"n":"Hardware","at":"INT","u":"YES"},{"n":"Programming","at":"INT","u":"YES"}]},{"n":"Demolitions","u":"YES","at":"INT","sp":[{"n":"Disarm","at":"INT","u":"YES"},{"n":"Set explosives","at":"INT","u":"YES"},{"n":"Scratch-Built Explosives","at":"INT","u":"NO"}]},{"n":"Law","u":"YES","at":"INT","sp":[{"n":"Court procedures","at":"INT","u":"YES"},{"n":"Law enforcement procedures","at":"INT","u":"YES"},{"n":"Law, specific skill","at":"INT","u":"NO"}]},{"n":"Life Science","u":"YES","at":"INT","sp":[{"n":"Biology","at":"INT","u":"NO"},{"n":"Botany","at":"INT","u":"NO"},{"n":"Genetics","at":"INT","u":"NO"},{"n":"Xenology","at":"INT","u":"NO"},{"n":"Zoology","at":"INT","u":"NO"}]},{"n":"Medical Science","u":"NO","at":"INT","sp":[{"n":"Forensics","at":"INT","u":"NO"},{"n":"Medical Knowledge","at":"INT","u":"NO"},{"n":"Psychology","at":"INT","u":"NO"},{"n":"Surgery","at":"INT","u":"NO"},{"n":"Treatment","at":"INT","u":"NO"},{"n":"Xenomedicine","at":"INT","u":"NO"}]},{"n":"Navigation","u":"YES","at":"INT","sp":[{"n":"Astrogation-drivespace","at":"INT","u":"NO"},{"n":"Astrogation-system","at":"INT","u":"NO"},{"n":"Navigation-surface","at":"INT","u":"YES"}]},{"n":"Physical Science","u":"YES","at":"INT","sp":[{"n":"Astronomy","at":"INT","u":"NO"},{"n":"Chemistry","at":"INT","u":"NO"},{"n":"Physics","at":"INT","u":"NO"},{"n":"Planetology","at":"INT","u":"NO"}]},{"n":"Security","u":"YES","at":"INT","sp":[{"n":"Protection protocols","at":"INT","u":"YES"},{"n":"Security devices","at":"INT","u":"YES"}]},{"n":"System Operation","u":"YES","at":"INT","sp":[{"n":"Communications","at":"INT","u":"YES"},{"n":"Defenses","at":"INT","u":"YES"},{"n":"Engineering","at":"INT","u":"YES"},{"n":"Sensors","at":"INT","u":"YES"},{"n":"Weapons","at":"INT","u":"YES"}]},{"n":"Tactics","u":"YES","at":"INT","sp":[{"n":"Infantry tactics","at":"INT","u":"YES"},{"n":"Space tactics","at":"INT","u":"YES"},{"n":"Vehicle tactics","at":"INT","u":"YES"}]},{"n":"Technical Science","u":"YES","at":"INT","sp":[{"n":"Invention","at":"INT","u":"NO"},{"n":"Jury-rig","at":"INT","u":"NO"},{"n":"Repair","at":"INT","u":"NO"},{"n":"Technical Knowledge","at":"INT","u":"NO"}]},{"n":"Knowledge","u":"YES","at":"INT","sp":[{"n":"Computer Operation","at":"INT","u":"NO"},{"n":"Deduce","at":"INT","u":"YES"},{"n":"First Aid","at":"INT","u":"NO"},{"n":"Language","at":"INT","u":"NO"}]}]},
    {"a":"WIL","s":[{"n":"Animal Handling","u":"YES","at":"WIL","sp":[{"n":"Animal riding","at":"WIL","u":"YES"},{"n":"Animal training","at":"WIL","u":"YES"}]},{"n":"Awareness","u":"YES","at":"WIL","sp":[{"n":"Intuition","at":"WIL","u":"YES"},{"n":"Perception","at":"WIL","u":"YES"},{"n":"Psionic Sense","at":"WIL","u":"NO"}]},{"n":"Resolve","u":"YES","at":"WIL","sp":[{"n":"Mental resolve","at":"WIL","u":"YES"},{"n":"Physical resolve","at":"WIL","u":"YES"}]},{"n":"Investigate","u":"YES","at":"WIL","sp":[{"n":"Interrogate","at":"WIL","u":"YES"},{"n":"Search","at":"WIL","u":"YES"},{"n":"Track","at":"WIL","u":"YES"}]},{"n":"Street Smart","u":"YES","at":"WIL","sp":[{"n":"Criminal elements","at":"WIL","u":"YES"},{"n":"Street knowledge","at":"WIL","u":"YES"}]},{"n":"Teach","u":"YES","at":"WIL","sp":[{"n":"Specific field","at":"WIL","u":"NO"}]}]},
    {"a":"PER","s":[{"n":"Culture","u":"YES","at":"PER","sp":[{"n":"Diplomacy","at":"PER","u":"YES"},{"n":"Etiquette","at":"PER","u":"NO"},{"n":"First Encounter","at":"PER","u":"NO"}]},{"n":"Deception","u":"YES","at":"PER","sp":[{"n":"Bluff","at":"PER","u":"YES"},{"n":"Bribe","at":"PER","u":"YES"},{"n":"Gamble","at":"PER","u":"YES"}]},{"n":"Entertainment","u":"YES","at":"PER","sp":[{"n":"Act","at":"PER","u":"YES"},{"n":"Dance","at":"PER","u":"YES"},{"n":"Musical instrument","at":"PER","u":"NO"}]},{"n":"Leadership","u":"YES","at":"PER","sp":[{"n":"Command","at":"PER","u":"YES"},{"n":"Inspire","at":"PER","u":"NO"}]},{"n":"Interaction","u":"YES","at":"PER","sp":[{"n":"Bargain","at":"PER","u":"YES"},{"n":"Charm","at":"PER","u":"YES"},{"n":"Interview","at":"PER","u":"YES"},{"n":"Intimidate","at":"PER","u":"YES"},{"n":"Seduce","at":"PER","u":"YES"},{"n":"Taunt","at":"PER","u":"YES"}]}]}
]

# Psionic Skills Data
PSIONICS_DATA = [
    {"a":"CON","s":[{"n":"Biokinesis","u":"NO","at":"CON","sp":[{"n":"Bio-Armor","at":"CON","u":"NO"},{"n":"Bioweapon","at":"CON","u":"NO"},{"n":"Clamber","at":"CON","u":"NO"},{"n":"Control Metabolism","at":"CON","u":"NO"},{"n":"Heal","at":"CON","u":"NO"},{"n":"Intangibility","at":"CON","u":"NO"},{"n":"Morph","at":"CON","u":"NO"},{"n":"Rejuvenate","at":"CON","u":"NO"},{"n":"Shatter","at":"CON","u":"NO"},{"n":"Transfer Damage","at":"CON","u":"NO"}]}]},
    {"a":"INT","s":[{"n":"ESP","u":"NO","at":"INT","sp":[{"n":"Battle Mind","at":"INT","u":"NO"},{"n":"Clairaudience","at":"INT","u":"NO"},{"n":"Clairvoyance","at":"INT","u":"NO"},{"n":"Dream Hunt","at":"INT","u":"NO"},{"n":"Empathy","at":"INT","u":"NO"},{"n":"Mind Reading","at":"INT","u":"NO"},{"n":"Navcognition","at":"INT","u":"NO"},{"n":"Postcognition","at":"INT","u":"NO"},{"n":"Precognition","at":"INT","u":"NO"},{"n":"Psychometry","at":"INT","u":"NO"}]}]},
    {"a":"WIL","s":[{"n":"Telekinesis","u":"NO","at":"WIL","sp":[{"n":"Cryokinetics","at":"WIL","u":"NO"},{"n":"Electrokinetics","at":"WIL","u":"NO"},{"n":"Kinetic Blow","at":"WIL","u":"NO"},{"n":"Kinetic Shield","at":"WIL","u":"NO"},{"n":"Levitation","at":"WIL","u":"NO"},{"n":"Photokinetics","at":"WIL","u":"NO"},{"n":"Psychokinetics","at":"WIL","u":"NO"},{"n":"Pyrokinesis","at":"WIL","u":"NO"},{"n":"Sheya's Clutch","at":"WIL","u":"NO"}]},{"n":"Psychoportation","u":"NO","at":"WIL","sp":[{"n":"Alter Speed","at":"WIL","u":"NO"},{"n":"Apportation","at":"WIL","u":"NO"},{"n":"Duplicate","at":"WIL","u":"NO"},{"n":"Timeslip","at":"WIL","u":"NO"},{"n":"Teleportation","at":"WIL","u":"NO"}]}]},
    {"a":"PER","s":[{"n":"Telepathy","u":"NO","at":"PER","sp":[{"n":"Contact","at":"PER","u":"NO"},{"n":"Datalink","at":"PER","u":"NO"},{"n":"Drain","at":"PER","u":"NO"},{"n":"Empathic Projection","at":"PER","u":"NO"},{"n":"Guidance","at":"PER","u":"NO"},{"n":"Illusion","at":"PER","u":"NO"},{"n":"Mind Blast","at":"PER","u":"NO"},{"n":"Mind Shield","at":"PER","u":"NO"},{"n":"Mind Wipe","at":"PER","u":"NO"},{"n":"Psychic Armor","at":"PER","u":"NO"},{"n":"Psychic Projection","at":"PER","u":"NO"},{"n":"Subdual","at":"PER","u":"NO"},{"n":"Suggest","at":"PER","u":"NO"},{"n":"Tire","at":"PER","u":"NO"},{"n":"Undo","at":"PER","u":"NO"}]}]}
]

ABILITY_MAP = {
    "STR": "Strength",
    "DEX": "Dexterity",
    "CON": "Constitution",
    "INT": "Intelligence",
    "WIL": "Will",
    "PER": "Personality",
    "CHA": "Personality"
}
