baseURL = 'http://localhost:1313/'
defaultContentLanguage = 'en'
title = 'AAA'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    title = 'AAA'

  [languages.es]
    languageName = 'Español'
    weight = 2
    title = 'AAA'

[params]
  custom_css = ["css/scifi.css", "css/custom.css"]
  body_classes = "scifi-body"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
