baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'AAA (Alterated Alternity Alternative)'
theme = 'ananke'

[params]
  custom_css = ["css/scifi.css"]
  body_classes = "scifi-body"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
